# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-16 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APICall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('method', models.CharField(choices=[('get', 'GET'), ('post', 'POST'), ('put', 'PUT'), ('patch', 'PATCH'), ('delete', 'DELETE'), ('head', 'HEAD'), ('trace', 'TRACE'), ('options', 'OPTIONS')], max_length=10, verbose_name='method')),
                ('request_headers', models.TextField(blank=True, verbose_name='request headers')),
                ('request_data', models.TextField(blank=True, verbose_name='request data')),
                ('files', models.TextField(blank=True, verbose_name='files')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended at')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='status_code')),
                ('response_headers', models.TextField(blank=True, verbose_name='response headers')),
                ('response_text', models.TextField(blank=True, verbose_name='response text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'ordering': ['-started_at'],
                'verbose_name': 'API Call',
                'verbose_name_plural': 'API Calls',
            },
        ),
    ]
