# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-13 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportlog',
            name='report',
        ),
        migrations.AddField(
            model_name='reportlog',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV')], default='---', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportlog',
            name='ordering',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportlog',
            name='report_type',
            field=models.CharField(choices=[('captable', 'Active Shareholders')], default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
