# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-14 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20170413_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='generation_time',
            field=models.PositiveIntegerField(default=0, verbose_name='time it took to generate the file in seconds'),
            preserve_default=False,
        ),
    ]
