# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-14 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20170414_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='generated_at',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='file creation datetime'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='ordering',
            field=models.CharField(choices=[('user__last_name', 'Last Name'), ('user__last_name_desc', 'Last Name (descending)'), ('share_count', 'Share Count'), ('share_count_desc', 'Share Count (descending)'), ('number', 'Shareholder Number'), ('number_desc', 'Shareholder Number (descending)'), ('share_percent', 'Share Percent Ownership'), ('share_percent_desc', 'Share Percent Ownership (descending)')], max_length=255),
        ),
    ]
