# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-14 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20170414_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='file creation datetime'),
        ),
    ]
