# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-15 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20170414_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='ordering',
            new_name='order_by',
        ),
    ]
