# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-12 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20170502_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='order_by',
            field=models.CharField(choices=[('user__last_name', 'Last Name'), ('user__last_name_desc', 'Last Name (descending)'), ('get_full_name', 'Last Name'), ('get_full_name_desc', 'Last Name (descending)'), ('share_count', 'Share Count'), ('share_count_desc', 'Share Count (descending)'), ('number', 'Shareholder Number'), ('number_desc', 'Shareholder Number (descending)'), ('share_percent', 'Share Percent Ownership'), ('share_percent_desc', 'Share Percent Ownership (descending)')], max_length=255),
        ),
    ]
