# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-30 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20170512_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('XLS', 'XLS')], max_length=3),
        ),
        migrations.AlterField(
            model_name='report',
            name='order_by',
            field=models.CharField(choices=[('user__last_name', 'Last Name'), ('user__last_name_desc', 'Last Name (descending)'), ('get_full_name', 'Last Name'), ('get_full_name_desc', 'Last Name (descending)'), ('share_count', 'Share Count'), ('share_count_desc', 'Share Count (descending)'), ('number', 'Shareholder Number'), ('number_desc', 'Shareholder Number (descending)'), ('share_percent', 'Share Percent Ownership'), ('share_percent_desc', 'Share Percent Ownership (descending)'), ('cumulated_face_value', 'face value total capital'), ('cumulated_face_value_desc', 'face value total capital (descending)'), ('user__userprofile__postal_code', 'postal code'), ('user__userprofile__postal_code_desc', 'postal code (descending)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('captable', 'Active Shareholders'), ('assembly_participation', 'Assembly Participation'), ('address_data', 'Address data of all shareholders'), ('certificates', 'Printed Certificates'), ('vested_shares', 'Vested Shares')], max_length=100),
        ),
    ]
