# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 17:30
from __future__ import unicode_literals

from datetime import date

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_statement_sending_for_companies(apps, schema_editor):
    """
    set date to last date of this year for existing companies, but disable
    sending for now (let operators decide)
    """
    Company = apps.get_model('shareholder', 'Company')
    statement_sending_date = date(date.today().year, 12, 31)  # December 31st
    for company in Company.objects.all():
        company.statement_sending_date = statement_sending_date
        company.is_statement_sending_enabled = False
        company.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shareholder', '0044_auto_20160720_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareholderStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FilePathField(match=b'*.pdf', max_length=500, path=settings.BASE_DIR + b'/media_restricted/shareholder/statements', recursive=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='email sent at')),
                ('email_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='email opened at')),
                ('pdf_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='PDF downloaded at')),
                ('letter_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='letter sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'shareholder statement',
                'verbose_name_plural': 'shareholder statements',
            },
        ),
        migrations.CreateModel(
            name='ShareholderStatementReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='report date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'shareholder statement report',
                'verbose_name_plural': 'shareholder statement reports',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='is_statement_sending_enabled',
            field=models.BooleanField(default=True, verbose_name='Is statement sending enabled'),
        ),
        migrations.AddField(
            model_name='company',
            name='statement_sending_date',
            field=models.DateField(blank=True, null=True, verbose_name='statement sending date'),
        ),
        migrations.AddField(
            model_name='shareholderstatementreport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareholder.Company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='shareholderstatement',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareholder.ShareholderStatementReport', verbose_name='shareholder statement report'),
        ),
        migrations.AddField(
            model_name='shareholderstatement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='shareholderstatement',
            unique_together=set([('report', 'user')]),
        ),

        # data migration
        migrations.RunPython(set_statement_sending_for_companies)
    ]
