# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-13 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0044_auto_20160720_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontransaction',
            name='certificate_id',
            field=models.CharField(blank=True, help_text='id of the issued certificate', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Nominalwert (bei Kapitalerh\xf6hung) oder Kaufpreis'),
        ),
        migrations.AlterField(
            model_name='security',
            name='face_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Nominalwert'),
        ),
        migrations.AlterField(
            model_name='security',
            name='title',
            field=models.CharField(choices=[(b'P', 'Vorzugsaktien'), (b'C', 'Stammaktien'), (b'R', 'Registered Shares')], max_length=1),
        ),
        migrations.AlterField(
            model_name='security',
            name='track_numbers',
            field=models.BooleanField(default=False, verbose_name='Aktiennummern sollen verfolgt werden. WARNUNG: bei Aktivierung aktualisieren sie bitte auch alle vorhandenen Transaktionen f\xfcr dieses Wertpapier!'),
        ),
    ]
