# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-05 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0045_auto_20161213_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='legal_type',
            field=models.CharField(choices=[(b'H', 'Human Being'), (b'C', 'Corporate')], default=b'H', help_text='legal type of the user', max_length=1),
        ),
        migrations.AlterField(
            model_name='optiontransaction',
            name='certificate_id',
            field=models.CharField(blank=True, help_text='Nummer des Zertifikates', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='title',
            field=models.CharField(choices=[(b'P', 'Vorzugsaktien'), (b'C', 'Stammaktien'), (b'R', 'Namensaktien')], max_length=1),
        ),
    ]
