# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-06 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0046_auto_20170105_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='registration_type',
            field=models.CharField(choices=[(b'1', 'Personal ownership'), (b'2', 'Personal representation')], default=b'1', max_length=1, verbose_name='Securities are purchase type (for myself, etc.)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='legal_type',
            field=models.CharField(choices=[(b'H', 'Nat\xfcrliche Person'), (b'C', 'Juristische Person')], default=b'H', help_text='Rechtsf\xe4higkeit / Aktion\xe4rsart', max_length=1),
        ),
    ]
