# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-06 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0047_auto_20170106_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='registration_type',
            field=models.CharField(blank=True, choices=[(b'1', 'Eigenbestand'), (b'2', 'Eigene Rechnung')], default=b'1', max_length=1, null=True, verbose_name='Wertpapiererwerb f\xfcr ...'),
        ),
    ]
