# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-10 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0051_auto_20170109_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pobox_id',
        ),
    ]
