# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0052_auto_20161112_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name', 'iso_code'], 'verbose_name': 'Land', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shareholder.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shareholder.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street'),
        ),
    ]
