# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-11 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0053_auto_20170110_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholder',
            name='mailing_type',
            field=models.CharField(blank=True, choices=[(b'0', 'Unzustellbar'), (b'1', 'Papier'), (b'2', 'E-Mail-Adresse')], max_length=1, null=True, verbose_name='how should the shareholder be approached by the corp'),
        ),
    ]
