# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-11 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0054_shareholder_mailing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='cusip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='public security id aka Valor, WKN, CUSIP: http://bit.ly/2ieXwuK'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='mailing_type',
            field=models.CharField(blank=True, choices=[(b'0', 'Unzustellbar'), (b'1', 'Briefversand'), (b'2', 'Emailversand')], max_length=1, null=True, verbose_name='Wie soll der Aktion\xe4r durch die Gesellschaft kontaktiert werden?'),
        ),
    ]
