# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-12 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0055_auto_20170111_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontransaction',
            name='depot_type',
            field=models.CharField(blank=True, choices=[(b'0', 'Zertifikatsdepot'), (b'1', 'Gesellschaftsdepot'), (b'2', 'Sperrdepot')], max_length=1, null=True, verbose_name='What kind of depot is this position stored within'),
        ),
        migrations.AddField(
            model_name='optiontransaction',
            name='stock_book_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='aka Skontro (read http://bit.ly/2iJquEl)'),
        ),
        migrations.AddField(
            model_name='position',
            name='depot_type',
            field=models.CharField(blank=True, choices=[(b'0', 'Zertifikatsdepot'), (b'1', 'Gesellschaftsdepot'), (b'2', 'Sperrdepot')], max_length=1, null=True, verbose_name='What kind of depot is this position stored within'),
        ),
        migrations.AddField(
            model_name='position',
            name='stock_book_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='aka Skontro (read http://bit.ly/2iJquEl)'),
        ),
    ]
