# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import shareholder.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0057_auto_20161110_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholderstatement',
            name='remote_email_id',
            field=models.CharField(blank=True, help_text='Prefix id with provider, e.g. mandrill$[EMAIL_ID]', max_length=200, validators=[shareholder.validators.validate_remote_email_id], verbose_name='remote email id'),
        )
    ]
