# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-02 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0058_company_vote_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='initial_registration_at',
            field=models.DateField(blank=True, null=True, verbose_name='when did the user register with the share register 1st time.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='vote_ratio',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Stimmrechteberechnung: eine Stimme pro CHF des Nennwertes der Aktie'),
        ),
    ]
