# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-11 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0060_auto_20170211_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optiontransaction',
            name='is_printed',
        ),
        migrations.AddField(
            model_name='optiontransaction',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='was this printed at least once?'),
        ),
    ]
