# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-11 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import shareholder.models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0061_auto_20170211_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pdf_header_image',
            field=models.ImageField(blank=True, null=True, upload_to=shareholder.models.get_company_header_image_upload_path),
        ),
    ]
