# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-11 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0064_auto_20170212_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='certificate_id',
            field=models.CharField(blank=True, help_text='Nummer des Zertifikates', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum des ersten Drucks'),
        ),
        migrations.AlterField(
            model_name='company',
            name='signatures',
            field=models.CharField(blank=True, max_length=255, verbose_name='Komma-separierte Liste von VR Mitgliedern, welche die Zertifikate unterzeichnen'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='is_management',
            field=models.BooleanField(default=False, verbose_name='Gesellschafter ist Mitglied des VR/Managements'),
        ),
    ]
