# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-19 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0066_operator_last_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_multi_company_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
