# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-13 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0067_userprofile_is_multi_company_allowed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['company__name']},
        ),
        migrations.AlterField(
            model_name='security',
            name='title',
            field=models.CharField(choices=[(b'P', 'Vorzugsaktien'), (b'C', 'Stammaktien'), (b'R', 'Namensaktien'), (b'V', 'Registered share with restricted transferability')], default=b'C', max_length=1),
        ),
    ]
