# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-22 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0068_auto_20170322_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='street',
            new_name='address',
        ),
    ]
