# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-23 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0069_auto_20170322_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='depot_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shareholder.Bank'),
        ),
    ]
