# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-23 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0070_position_depot_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='certificate_invalidat_position',
            field=models.OneToOneField(blank=True, help_text='assigned position represents the change back to company depot from cert depot', null=True, on_delete=django.db.models.deletion.CASCADE, to='shareholder.Position'),
        ),
    ]
