# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-23 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0071_position_certificate_invalidat_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='certificate_invalidat_position',
            new_name='certificate_invalidation_position',
        ),
    ]
