# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-14 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0073_auto_20170327_0834'),
        ('shareholder', '0068_auto_20170413_2024'),
    ]

    operations = [
    ]
