# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-21 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0068_auto_20170113_0923'),
        ('shareholder', '0075_auto_20170421_0854'),
    ]

    operations = [
    ]
