# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-23 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0076_merge_20170421_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholderstatement',
            name='pdf_file',
            field=models.FilePathField(match=b'.+\\.pdf', max_length=500, path=b'media/private/shareholder/statements', recursive=True),
        ),
    ]
