# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-28 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0077_auto_20170423_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholderstatementreport',
            name='pdf_file',
            field=models.FilePathField(blank=True, match=b'.+\\.pdf', max_length=500, null=True, path=b'media/private/shareholder/statements', recursive=True),
        ),
    ]
