# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-29 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shareholder.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0078_shareholderstatementreport_pdf_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Unternehmen', 'verbose_name_plural': 'Unternehmen'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name', 'iso_code'], 'verbose_name': 'Land', 'verbose_name_plural': 'L\xe4nder'},
        ),
        migrations.AlterModelOptions(
            name='shareholderstatement',
            options={'verbose_name': 'Depotausz\xfcge', 'verbose_name_plural': 'Depotausz\xfcge'},
        ),
        migrations.AlterModelOptions(
            name='shareholderstatementreport',
            options={'verbose_name': 'Bericht Depotausz\xfcge', 'verbose_name_plural': 'Berichte Depotausz\xfcge'},
        ),
        migrations.AddField(
            model_name='company',
            name='send_shareholder_statement_via_letter_enabled',
            field=models.BooleanField(default=False, verbose_name='Is sending the shareholder statement via snail mail enabled'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_statement_sending_enabled',
            field=models.BooleanField(default=True, verbose_name='Versand der Depotausz\xfcge ist aktiviert'),
        ),
        migrations.AlterField(
            model_name='company',
            name='statement_sending_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum f\xfcr Versand der Kontoausz\xfcge'),
        ),
        migrations.AlterField(
            model_name='shareholderstatement',
            name='email_opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email ge\xf6ffnet am'),
        ),
        migrations.AlterField(
            model_name='shareholderstatement',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email gesendet am'),
        ),
        migrations.AlterField(
            model_name='shareholderstatement',
            name='letter_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Brief versendet am'),
        ),
        migrations.AlterField(
            model_name='shareholderstatement',
            name='pdf_downloaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PDF heruntergeladen am'),
        ),
        migrations.AlterField(
            model_name='shareholderstatement',
            name='remote_email_id',
            field=models.CharField(blank=True, help_text='Prefix ID mit Provider, z.B.  mandrill$[EMAIL_ID]', max_length=200, validators=[shareholder.validators.validate_remote_email_id], verbose_name='Remote Email ID'),
        ),
        migrations.AlterField(
            model_name='shareholderstatement',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareholder.ShareholderStatementReport', verbose_name='Bericht Depotausz\xfcge'),
        ),
        migrations.AlterField(
            model_name='shareholderstatementreport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareholder.Company', verbose_name='Unternehmen'),
        ),
        migrations.AlterField(
            model_name='shareholderstatementreport',
            name='report_date',
            field=models.DateField(verbose_name='Berichtsdatum'),
        ),
    ]
