# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-01 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0079_auto_20170429_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='send_shareholder_statement_via_letter_enabled',
            field=models.BooleanField(default=False, verbose_name='Das Senden der Depotausz\xfcge per Brief/Post ist aktiviert'),
        ),
    ]
