# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-04 18:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0080_auto_20170501_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholder',
            name='order_cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='cache data for fast sorting here'),
        ),
    ]
