# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-22 19:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0081_shareholder_order_cache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='security',
            options={'ordering': ['face_value']},
        ),
        migrations.AddField(
            model_name='company',
            name='support_contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='string with comma separated names for support contact printed inside statement'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='order_cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='gecachte Daten f\xfcr schnelleres Sortieren'),
        ),
    ]
